#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC
login=$YNH_APP_ARG_LOGIN

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Save app settings
ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" is_public "$is_public"

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Install dependencies
if ! ynh_package_is_installed "php5-sqlite" ; then
    ynh_package_install php5-sqlite
fi

# Copy source files
src_path=/var/www/$app
sudo mkdir -p $src_path
sudo wget -q -P "$src_path" http://projekte.textmulch.de/bicbucstriim/downloads/BicBucStriim-1.3.6.zip -O "$src_path"/bbs.zip
sudo unzip -q "$src_path"/bbs.zip -d "$src_path"
sudo cp -R "$src_path"/BicBucStriim-1.3.6/* "$src_path"
sudo rm "$src_path"/bbs.zip
sudo rm -rf "$src_path"/BicBucStriim-1.3.6

books_path=${src_path}_library
cp -r ../empty_library $books_path

# Disable BicBucStriim login if checked
if [[ $login -eq 1 ]]; then
  sudo sed -i -- 's/\[LOGIN_REQUIRED\] = 1/\[LOGIN_REQUIRED\] = 0/g' "$src_path"/index.php
fi

# Set permissions to app files
sudo chown -R root: $src_path
sudo chmod -R ga+w $src_path/data

if ! ynh_package_is_installed "sqlite3" ; then
    ynh_package_install sqlite3
    echo "INSERT INTO config (name, val) VALUES ('calibre_dir', '/var/www/bicbucstriim_library');" | sqlite3 $src_path/data/data.db
    ynh_package_remove sqlite3
else
    echo "INSERT INTO config (name, val) VALUES ('calibre_dir', '/var/www/bicbucstriim_library');" | sqlite3 $src_path/data/data.db
fi

# Modify Nginx configuration file and copy it to Nginx conf directory
nginx_conf=../conf/nginx.conf
sed -i "s@YNH_WWW_PATH@$path@g" $nginx_conf
sed -i "s@YNH_WWW_ALIAS@$src_path/@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
  # unprotected_uris allows SSO credentials to be passed anyway.
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

# Reload services
sudo service nginx reload
echo "Open $domain$path/installcheck.php for troubleshooting guide."
echo "Default login and password are admin/admin. Change it!"
